import type { GlobalTheme } from '../hooks/useWorkspaceTheme';

export interface WorkspaceAppearancePreset {
  id: string;
  name: string;
  emoji: string;
  description: string;
  atmosphereId: string;
  /** Mini preview swatches */
  preview: { page: string; card: string; accent: string };
  theme: Partial<GlobalTheme>;
}

export const WORKSPACE_APPEARANCE_PRESETS: WorkspaceAppearancePreset[] = [
  {
    id: 'deep-focus',
    name: 'Deep Focus',
    emoji: '🌑',
    description: 'OLED calm. Minimal glow. Maximum clarity.',
    atmosphereId: 'deep-focus',
    preview: { page: '#0d0b10', card: '#17141b', accent: '#818cf8' },
    theme: {
      accentPreset: 'violet',
      backgroundStyle: 'minimal-black',
      surfaceStyle: 'solid',
      glowIntensity: 'off',
      gridVisible: true,
      ambientIntensity: 0.22,
      fogLevel: 0.18,
      focusStrength: 'soft',
      cardSolidity: 0.95,
      spatialContrast: 0.8,
    },
  },
  {
    id: 'warm-studio',
    name: 'Warm Studio',
    emoji: '☀️',
    description: 'Amber warmth. Solid desks. Daily comfort.',
    atmosphereId: 'neural',
    preview: { page: '#14100c', card: '#201b14', accent: '#f59e0b' },
    theme: {
      accentPreset: 'amber',
      backgroundStyle: 'warm-study',
      surfaceStyle: 'solid',
      glowIntensity: 'low',
      gridVisible: true,
      ambientIntensity: 0.32,
      fogLevel: 0.22,
      focusStrength: 'soft',
      cardSolidity: 0.92,
      spatialContrast: 0.75,
    },
  },
  {
    id: 'midnight',
    name: 'Midnight',
    emoji: '🌙',
    description: 'Cool violet depth. Quiet contrast.',
    atmosphereId: 'deep-focus',
    preview: { page: '#0d0b10', card: '#17141b', accent: '#a5b4fc' },
    theme: {
      accentPreset: 'violet',
      backgroundStyle: 'deep-night',
      surfaceStyle: 'soft-card',
      glowIntensity: 'low',
      gridVisible: false,
      ambientIntensity: 0.28,
      fogLevel: 0.24,
      focusStrength: 'soft',
      cardSolidity: 0.9,
      spatialContrast: 0.7,
    },
  },
  {
    id: 'neural',
    name: 'Neural',
    emoji: '⚡',
    description: 'Signature amber signal on warm charcoal.',
    atmosphereId: 'neural',
    preview: { page: '#14100c', card: '#201b14', accent: '#f59e0b' },
    theme: {
      accentPreset: 'amber',
      backgroundStyle: 'warm-study',
      surfaceStyle: 'soft-card',
      glowIntensity: 'low',
      gridVisible: true,
      ambientIntensity: 0.35,
      fogLevel: 0.26,
      focusStrength: 'soft',
      cardSolidity: 0.88,
      spatialContrast: 0.72,
    },
  },
  {
    id: 'paper-dark',
    name: 'Paper Dark',
    emoji: '📄',
    description: 'Muted paper tone. Easy on the eyes.',
    atmosphereId: 'minimal-zen',
    preview: { page: '#161514', card: '#22201e', accent: '#d4a574' },
    theme: {
      accentPreset: 'amber',
      backgroundStyle: 'minimal-black',
      surfaceStyle: 'solid',
      glowIntensity: 'off',
      gridVisible: true,
      ambientIntensity: 0.2,
      fogLevel: 0.16,
      focusStrength: 'soft',
      cardSolidity: 0.96,
      spatialContrast: 0.82,
    },
  },
  {
    id: 'calm-amber',
    name: 'Calm Amber',
    emoji: '🍯',
    description: 'Gentle gold. Spacious and grounded.',
    atmosphereId: 'neural',
    preview: { page: '#14100c', card: '#201b14', accent: '#fbbf24' },
    theme: {
      accentPreset: 'amber',
      backgroundStyle: 'soft-gradient',
      surfaceStyle: 'soft-card',
      glowIntensity: 'low',
      gridVisible: false,
      ambientIntensity: 0.3,
      fogLevel: 0.2,
      focusStrength: 'soft',
      cardSolidity: 0.9,
      spatialContrast: 0.74,
    },
  },
  {
    id: 'electric-blue',
    name: 'Electric Blue',
    emoji: '⚡',
    description: 'Cool cyan focus. Crisp spatial edges.',
    atmosphereId: 'calm-night',
    preview: { page: '#13161a', card: '#1d232a', accent: '#38bdf8' },
    theme: {
      accentPreset: 'cyan',
      backgroundStyle: 'grid-canvas',
      surfaceStyle: 'solid',
      glowIntensity: 'low',
      gridVisible: true,
      ambientIntensity: 0.26,
      fogLevel: 0.2,
      focusStrength: 'soft',
      cardSolidity: 0.93,
      spatialContrast: 0.78,
    },
  },
  {
    id: 'soft-graphite',
    name: 'Soft Graphite',
    emoji: '◻️',
    description: 'Neutral gray. Zero drama.',
    atmosphereId: 'minimal-zen',
    preview: { page: '#121212', card: '#1a1a1a', accent: '#e8e8e8' },
    theme: {
      accentPreset: 'blue',
      backgroundStyle: 'minimal-black',
      surfaceStyle: 'solid',
      glowIntensity: 'off',
      gridVisible: true,
      ambientIntensity: 0.18,
      fogLevel: 0.14,
      focusStrength: 'soft',
      cardSolidity: 0.94,
      spatialContrast: 0.85,
    },
  },
  {
    id: 'research-lab',
    name: 'Research Lab',
    emoji: '🔬',
    description: 'Cool grid. High legibility. Tool-like.',
    atmosphereId: 'calm-night',
    preview: { page: '#13161a', card: '#1d232a', accent: '#60a5fa' },
    theme: {
      accentPreset: 'blue',
      backgroundStyle: 'grid-canvas',
      surfaceStyle: 'solid',
      glowIntensity: 'off',
      gridVisible: true,
      ambientIntensity: 0.24,
      fogLevel: 0.18,
      focusStrength: 'balanced',
      cardSolidity: 0.94,
      spatialContrast: 0.84,
    },
  },
  {
    id: 'creative-studio',
    name: 'Creative Studio',
    emoji: '✦',
    description: 'Violet studio energy. Still readable.',
    atmosphereId: 'creative',
    preview: { page: '#0f0c19', card: '#181427', accent: '#a78bfa' },
    theme: {
      accentPreset: 'violet',
      backgroundStyle: 'ambient-glow',
      surfaceStyle: 'soft-card',
      glowIntensity: 'low',
      gridVisible: false,
      ambientIntensity: 0.36,
      fogLevel: 0.3,
      focusStrength: 'balanced',
      cardSolidity: 0.86,
      spatialContrast: 0.68,
    },
  },
];

export function findAppearancePreset(id: string): WorkspaceAppearancePreset | undefined {
  return WORKSPACE_APPEARANCE_PRESETS.find(p => p.id === id);
}
