import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'happy-dom',
    include: [
      'src/lib/katexVisualExtract/**/*.test.ts',
      'src/lib/persistenceQa.test.ts',
      'src/lib/notebookImagePersist.test.ts',
      'src/lib/freeSpaceLocalMerge.test.ts',
      'src/lib/focusCacheNamespace.test.ts',
      'src/lib/focusCache/pendingOperations.test.ts',
      'src/lib/focusCache/freeSpaceObjectCreateEnqueue.test.ts',
      'src/lib/focusCache/freeSpaceObjectUpdateEnqueue.test.ts',
      'src/lib/focusCache/freeSpaceObjectDeleteCancel.test.ts',
      'src/lib/focusCache/freeSpaceObjectDeleteEnqueue.test.ts',
      'src/lib/focusCache/freeSpaceObjectCloud.test.ts',
      'src/lib/focusCache/freeSpaceObjectPull.test.ts',
      'src/lib/focusCache/freeSpaceObjectRealtime.test.ts',
      'src/lib/focusCache/flushPendingFreeSpaceCreates.test.ts',
      'src/lib/focusCache/freeSpaceObjectAutoFlush.test.ts',
      'src/lib/focusCache/freeSpaceObjectCreateDeleteRace.test.ts',
      'src/lib/focusCache/freeSpaceBoardEnqueue.test.ts',
      'src/lib/focusCache/freeSpaceBoardPull.test.ts',
      'src/lib/focusCache/freeSpaceBoardRealtime.test.ts',
      'src/lib/focusCache/freeSpaceBoardDeleteCascade.test.ts',
      'src/lib/focusCache/freeSpaceBoardSync.integration.test.ts',
      'src/lib/sync/**/*.test.ts',
      'src/lib/freeSpaceObjectGeometry.test.ts',
      'src/lib/freeSpaceLocalGeometryCommit.test.ts',
      'src/lib/focusCache/freeSpaceObjectGeometryLww.test.ts',
      'src/lib/focusCache/freeSpaceVisibilityResumeCatchUp.test.ts',
      'src/lib/viewportPersist.test.ts',
      'src/hooks/useSectionCanvasMode.test.ts',
      'src/lib/userContentStorage.test.ts',
      'src/lib/userContentAssetDescriptor.test.ts',
      'src/lib/userContentAssetFlush.test.ts',
      'src/lib/notebookHandwritingCloud.test.ts',
      'src/components/notebook/HandwritingBlock.cloudHydrate.test.tsx',
    ],
  },
});
