import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'happy-dom',
    setupFiles: ['fake-indexeddb/auto'],
    include: [
      'src/lib/katexVisualExtract/**/*.test.ts',
      'src/lib/persistenceQa.test.ts',
      'src/lib/notebookImagePersist.test.ts',
      'src/lib/freeSpaceLocalMerge.test.ts',
      'src/lib/focusCacheNamespace.test.ts',
      'src/lib/focusCache/pendingOperations.test.ts',
      'src/lib/focusCache/freeSpaceObjectCreateEnqueue.test.ts',
      'src/lib/focusCache/freeSpaceObjectUpdateEnqueue.test.ts',
      'src/lib/focusCache/freeSpaceObjectDeleteCancel.test.ts',
      'src/lib/focusCache/freeSpaceObjectDeleteEnqueue.test.ts',
      'src/lib/focusCache/freeSpaceObjectCloud.test.ts',
      'src/lib/focusCache/freeSpaceObjectPull.test.ts',
      'src/lib/focusCache/freeSpaceObjectRealtime.test.ts',
      'src/lib/focusCache/flushPendingFreeSpaceCreates.test.ts',
      'src/lib/focusCache/freeSpaceObjectAutoFlush.test.ts',
      'src/lib/focusCache/freeSpaceObjectCreateDeleteRace.test.ts',
      'src/lib/focusCache/freeSpaceBoardEnqueue.test.ts',
      'src/lib/focusCache/freeSpaceBoardPull.test.ts',
      'src/lib/focusCache/freeSpaceBoardRealtime.test.ts',
      'src/lib/focusCache/freeSpaceBoardDeleteCascade.test.ts',
      'src/lib/focusCache/freeSpaceBoardSync.integration.test.ts',
      'src/lib/sync/**/*.test.ts',
      'src/lib/freeSpaceObjectGeometry.test.ts',
      'src/lib/freeSpaceLocalGeometryCommit.test.ts',
      'src/lib/focusCache/freeSpaceObjectGeometryLww.test.ts',
      'src/lib/focusCache/freeSpaceVisibilityResumeCatchUp.test.ts',
      'src/lib/viewportPersist.test.ts',
      'src/hooks/useSectionCanvasMode.test.ts',
      'src/lib/userContentStorage.test.ts',
      'src/lib/userContentAssetDescriptor.test.ts',
      'src/lib/userContentAssetFlush.test.ts',
      'src/lib/notebookHandwritingCloud.test.ts',
      'src/lib/notebookImageCloud.test.ts',
      'src/lib/spatialAssetCloud.integration.test.ts',
      'src/lib/spatialAssetCloud.crossDevice.integration.test.ts',
      'src/lib/spatialAssetCloud.live.test.ts',
      'src/lib/freeSpaceImageObject.persistence.test.ts',
      'src/lib/freeSpacePdfObject.persistence.test.ts',
      'src/lib/pdfPageVisibility.test.ts',
      'src/lib/pdfViewerPagePropagate.test.ts',
      'src/lib/spatialAssetCloud.crossDevice.delete.integration.test.ts',
      'src/lib/spatialAssetCloud.crossDevice.pdfDelete.integration.test.ts',
      'src/lib/notebookDeleteCascade.test.ts',
      'src/lib/notebookPages.persistence.test.ts',
      'src/lib/notebookPages.crossDevice.integration.test.ts',
      'src/lib/notebookPages.live.test.ts',
      'src/lib/notebookPages/notebookWorkspaceChrome.test.ts',
      'src/lib/notebookCopySelection.test.ts',
      'src/lib/notebookToolbarCapture.test.ts',
      'src/lib/notebookCaret.test.ts',
      'src/lib/notebookInlineMarks.sequential.test.ts',
      'src/lib/notebookFormatHistory.test.ts',
      'src/lib/freeSpaceScalePolicy.test.ts',
      'src/lib/deriveMissionControlContinue.test.ts',
      'src/lib/missionControlContinueOpen.test.ts',
      'src/lib/freeSpaceNotebook.integration.test.tsx',
      'src/lib/freeSpaceNotebookToolbar.session.test.tsx',
      'src/lib/notebookMultiClickSelection.test.ts',
      'src/lib/notebookToolbarAnchor.test.ts',
      'src/lib/freeSpaceNotebookMultiClick.integration.test.tsx',
      'src/components/notebook/NotebookSelectionToolbar.interaction.test.tsx',
      'src/lib/crossDevicePersistence.integration.test.ts',
      'src/lib/desk/deskPersistence.test.ts',
      'src/lib/focusCache/userWorkspaceStateCloud.live.test.ts',
      'src/components/notebook/HandwritingBlock.cloudHydrate.test.tsx',
      'src/sheets/**/*.test.ts',
    ],
  },
});
